server:
  port: 8084
feign:
  okhttp:
    enabled: true
dymall:
  swagger:
    title: DyMall-用户服务
    package: top.hyperplasma.user.controller
  db:
    database: dymall-user
  jwt:
    location: classpath:dymall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
